name: Automated testing for scontents package (TL2026)

on:
  push:
    branches:
      - "*"
  schedule:
    - cron: "0 12 * * 5"
  workflow_dispatch:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    name: Check and Build
    strategy:
      fail-fast: false
      matrix:
        version:
          - 2026
        command:
          - doc
          - examples
          - testpkg
    steps:
      - name: Checkout
        uses: actions/checkout@v4

        - name: Install ghostscript and python3-pygments
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends ghostscript python3-pygments

      - name: Setup TeX Live ${{ matrix.version }}
        uses: zauguin/install-texlive@v4
        with:
          package_file: .github/tl_packages
          texlive_version: ${{ matrix.version }}

      - name: Install scontents package
        run: l3build install

      - name: Run "l3build ${{ matrix.command }}" (TeX Live ${{ matrix.version }})
        run: l3build ${{ matrix.command }}

      - name: Archive failed test output
        if: ${{ failure() }}
        uses: zauguin/l3build-failure-artifacts@v1
        with:
          name: testfiles-fillwith
          retention-days: 3
